package warnup1;

import java.util.HashMap;

public class Warmup1
{
	static HashMap<Integer, String> map = new HashMap<>(); // to make it faster
	
	public static void initialMap()
	{
		map.put(0, "F");
		return;
	}
	
	/**
	 * getDragon
	 * @param n
	 * 0 -> F
	 * 1 -> FLF
	 * 2 -> FLFLFRF
	 * 3 -> FLFLFRFLFLFRFRF
	 * 
	 * @return String
	 */
	public static String getDragon(int n)
	{
		if (map.containsKey(n))
			return map.get(n);
		else if (n < 0)
			return "It should not be a natural number. ";
		else
		{
			String str = getDragon(n - 1);
			StringBuffer sb = new StringBuffer();
			sb.append(str);
			sb.append("L");
			for (int i = str.length() - 1; i > -1; --i)
				switch (str.charAt(i))
				{
				case 'F':
				case 'f':
					sb.append('F');
					break;
				case 'L':
				case 'l':
					sb.append('R');
					break;
				case 'R':
				case 'r':
					sb.append('L');
					break;
				default: // Error
					return "Something unexpected happened. ";
				}
			map.put(n, sb.toString()); // save
			return sb.toString();
		}
	}
	
	/**
	 * main
	 * @param args
	 * String[] args = {"0", "1", "2", "3", "5", "10"};
	 * 
	 * 0 -> F
	 * 1 -> FLF
	 * 2 -> FLFLFRF
	 * 3 -> FLFLFRFLFLFRFRF
	 * 5 -> FLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRF
	 * 10 -> FLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFLFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFLFLFLFRFRFLFRFRFRFLFLFRFLFLFRFRFRFLFLFRFRFLFRFRF
	 * 
	 */
	public static void main(String[] args)
	{
		initialMap();
        for (String arg : args)
        {
        	try
        	{
        		int n = Integer.parseInt(arg);
        		System.out.println(n + " -> " + getDragon(n));
        	}
        	catch (Throwable e)
        	{
        		System.out.println("\"" + arg + "\" -> " + e);
        	}
        }
        return;
	}
}